### ISSUE TITLE
Yaml数字读取

### ISSUE THREAD

**Issue by Solaestas** [AmiyaBot/Amiya-Bot#268]
### 问题描述

当yaml中的密钥为纯数字时，authKey会是int类型，从而导致密钥永远匹配不上

### 复现

server.yaml
```yaml
host: 127.0.0.1
port: 8088
authKey: 114514
```

test.py
```python
from typing import *
from yamlManager import *

def Test(auth_key: str):
    if auth_key and "114514" != auth_key:
        print("Invalid AuthKey")

yaml = YamlManager.read_yaml("yaml.yaml")
Test(yaml.authKey)
```

### Amiya-Bot 版本

V6-master
